name: Fetch Police Crime JSON

on:
  schedule:
    - cron: '20 * * * *'   # UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-police-crime-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure data directory
        run: mkdir -p data

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Resolve the newest month the API has actually published
      - name: Resolve latest available month
        id: latest
        run: |
          set -euo pipefail
          latest=$(curl -s --fail https://data.police.uk/api/crimes-street-dates | jq -r '.[0].date')
          echo "date=$latest" >> "$GITHUB_OUTPUT"
          echo "Latest published month: $latest"

      - name: Fetch Police UK crime data
        run: |
          set -euo pipefail
          date="${{ steps.latest.outputs.date }}"
          file="data/police-crime-${date}.json"
          url="https://data.police.uk/api/crimes-street/all-crime?lat=51.55761&lng=0.073477&date=${date}"

          echo "GET $url"
          http_code=$(curl -w "%{http_code}" --fail --location --retry 5 --retry-delay 5 -s "$url" -o "$file")
          echo "HTTP $http_code"

          # Validate JSON (non-empty and an array)
          test -s "$file"
          jq . "$file" > /dev/null
          jq -e 'type == "array"' "$file" > /dev/null

          echo "Preview:"
          head -n 5 "$file" || true

      - name: Generate summary.md
        run: |
          set -euo pipefail
          date="${{ steps.latest.outputs.date }}"
          file="data/police-crime-${date}.json"
          summary="summary.md"

          total=$(jq 'length' "$file")
          if [ "$total" -eq 0 ]; then
            top=""
          else
            top=$(jq -r '.[].category // empty' "$file" | sort | uniq -c | sort -nr | head -5)
          fi

          {
            echo "# Crime Data Summary"
            echo
            echo "**Date:** ${date}"
            echo
            echo "- Total crimes: $total"
            echo
            echo "## Top 5 categories"
            if [ -n "$top" ]; then
              echo '```'
              echo "$top"
              echo '```'
            else
              echo "_No category data available for this month._"
            fi
          } > "$summary"

      - name: Upload summary artifact (for easy viewing)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: summary-${{ steps.latest.outputs.date }}
          path: summary.md

      - name: Commit and push JSON data + summary
        run: |
          set -euo pipefail
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git add "data/police-crime-${{ steps.latest.outputs.date }}.json" summary.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git pull --rebase --autostash origin "${GITHUB_REF_NAME}" || true
            git commit -m "chore(data): add police crime data & summary for ${{ steps.latest.outputs.date }}"
            git push
          fi
