name: Fetch Police Crime JSON

on:
  schedule:
    - cron: '20 * * * *'   # runs at :20 past every hour (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-police-crime-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure data directory
        run: mkdir -p data

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set current month and year
        id: date
        run: echo "date=$(date +'%Y-%m')" >> "$GITHUB_OUTPUT"

      - name: Fetch Police UK crime data
        run: |
          set -euo pipefail
          file="data/police-crime-${{ steps.date.outputs.date }}.json"
          curl --fail --location --retry 5 --retry-delay 5 -s \
            "https://data.police.uk/api/crimes-street/all-crime?lat=51.55761&lng=0.073477&date=${{ steps.date.outputs.date }}" \
            -o "$file"

          # Validate JSON (non-empty + valid)
          test -s "$file"
          jq . "$file" > /dev/null

          # Show a small preview for debugging
          echo "File content preview:"
          head -n 5 "$file" || echo "File not found or empty"

      - name: Generate summary.md
        run: |
          set -euo pipefail
          file="data/police-crime-${{ steps.date.outputs.date }}.json"
          summary="summary.md"

          # Count total crimes (handles empty array)
          total=$(jq 'length' "$file")

          # Top 5 categories (handles empty array safely)
          top=$(jq -r '.[].category // empty' "$file" | sort | uniq -c | sort -nr | head -5)

          {
            echo "# Crime Data Summary"
            echo
            echo "**Date:** ${{ steps.date.outputs.date }}"
            echo
            echo "- Total crimes: $total"
            echo
            echo "## Top 5 categories"
            if [ -n "$top" ]; then
              echo '```'
              echo "$top"
              echo '```'
            else
              echo "_No category data available for this month._"
            fi
          } > "$summary"

      - name: Commit and push JSON data + summary
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git add "data/police-crime-${{ steps.date.outputs.date }}.json" summary.md

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            echo "Changes detected; committing."
            git commit -m "chore(data): add police crime data & summary for ${{ steps.date.outputs.date }}"
            git push
          fi
